name: Build Models

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install OpenSCAD
      run: sudo apt-get install -y openscad
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Cache STL Files
      id: cache-stl
      uses: actions/cache@v3
      with:
        path: cache
        key: stlcache-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          stlcache-${{ runner.os }}
    - name: read cache
      run: .github/workflows/getcache
    - name: build
      run: make
    - name: create cache
      run: .github/workflows/mkcache
